### ISSUE TITLE
UI Error (App Still Functional)

### ISSUE THREAD

**Issue by jxhallaxoun** [jimmyatSplunk/splunk_app_for_bigfix#2]
Receive this error when loading the overview page:
Splunk has failed to locate the template for uri '/APP/splunk-app-for-bigfix/appserver/static/BigFixSearch.html'.

Is this a configuration issue on my end?

**Comment by jimmyatSplunk** [comment]
When you installed the app, did you remove the "-master" suffix from the app parent directory? The  name of the parent directory in "$SPLUNK_HOME/etc/apps" should be "splunk_app_for_bigfix".

An unfortunate side-effect of the hosting the app on GitHub I'm afraid.

**Comment by jxhallaxoun** [comment]
I'll check but I had gone and altered the path in the archive before installing after having the same issue with the ta plugin. It's just failing to show the search box which really isn't a dealkiller. I'm also missing some analyses so that may be part of it.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jimmyatSplunk** [comment]
Going to assume that since it's been many months since this was opened with no further comment that the renaming of the app folder corrected the issue.
